### ISSUE TITLE
Missing Documentation Page: collaboration

### ISSUE THREAD

**Issue by digitalvillainy** [sroehrl/neoan3docs#18]
The following link: 
http://neoan.us/neoan3docs/collaboration/

Has a 404 message. I wish to fix this.

**Comment by baedyl** [comment]
I am interested in this one. What exactly should the page contain ?

**Comment by sroehrl** [comment]
There is no defined format as of now. You will require understanding of git as well as the publishing functionality of the cli-tool.
In general, I want people to understand 

- how every component, model or frame can be it's own versioned repo defining its own dependencies (have a look at e.g. [user-model](https://github.com/sroehrl/neoan3-userModel) as a good entry)

- how these repositories are updated, packaged and or shared to be used

- via GIT or a capable IDE

_NOTE_: We are aiming at a starting point here. No need for perfection, but your content should be accurate and grammatically sound. Thank you for your interest
